exports.subjectMap = {
  AAS: 'Asian American Studies',
  AEM: 'Applied Economics & Management',
  AEP: 'Applied & Engineering Physics',
  AGSCI: 'Agricultural Sciences',
  AIIS: 'American Indian and Indigenous Studies',
  AIRS: 'Aerospace Studies',
  AKKAD: 'Akkadian',
  ALS: 'Agriculture & Life Sciences',
  AMST: 'American Studies',
  ANSC: 'Animal Science',
  ANTHR: 'Anthropology',
  ARAB: 'Arabic',
  ARCH: 'Architecture',
  ARKEO: 'Archaeology',
  ART: 'Art',
  ARTH: 'History of Art',
  AS: 'Arts & Sciences',
  ASIAN: 'Asian Studies',
  ASL: 'American Sign Language',
  ASRC: 'Africana Studies & Research Center',
  ASTRO: 'Astronomy',
  BCS: 'Bosnian, Croatian, Serbian',
  BEE: 'Biological & Environmental Engineering',
  BENGL: 'Bengali',
  BIOAP: 'Animal Physiology & Anatomy',
  BIOEE: 'Ecology & Evolutionary Biology',
  BIOG: 'Biology: General Courses',
  BIOMG: 'Molecular Biology and Genetics',
  BIOMI: 'Microbiology',
  BIOMS: 'Biomedical Sciences',
  BIONB: 'Neurobiology & Behavior',
  BME: 'Biomedical Engineering',
  BSOC: 'Biology & Society',
  BTRY: 'Biometry & Statistics',
  BURM: 'Burmese',
  CAPS: 'China & Asia Pacific Studies',
  CEE: 'Civil & Environmental Engineering',
  CHEM: 'Chemistry',
  CHEME: 'Chemical Engineering',
  CHIN: 'Chinese',
  CHLIT: 'Chinese Literature',
  CLASS: 'Classics',
  COGST: 'Cognitive Science',
  COLLS: 'College Scholar Program',
  COML: 'Comparative Literature',
  COMM: 'Communication',
  CRP: 'City & Regional Planning',
  CS: 'Computer Science',
  CZECH: 'Czech',
  DEA: 'Design & Environmental Analysis',
  DESIGN: 'Design',
  DSOC: 'Development Sociology',
  DUTCH: 'Dutch',
  EAS: 'Earth & Atmospheric Sciences',
  ECE: 'Electrical & Computer Engineering',
  ECON: 'Economics',
  EDUC: 'Education',
  ELSO: 'English Language Support',
  ENGL: 'English',
  ENGRC: 'Engineering Communications',
  ENGRD: 'Engineering Distribution',
  ENGRG: 'Engineering General Interest',
  ENGRI: 'Engineering Introduction',
  ENMGT: 'Engineering Management',
  ENTOM: 'Entomology',
  ENVS: 'Environment & Sustainability',
  FDSC: 'Food Science',
  FGSS: 'Feminist, Gender & Sexuality Studies',
  FINN: 'Finnish',
  FREN: 'French',
  FSAD: 'Fiber Science & Apparel Design',
  GERST: 'German Studies',
  GOVT: 'Government',
  GRAD: 'Graduate Research',
  GREEK: 'Greek',
  HADM: 'Hotel Administration',
  HD: 'Human Development',
  HE: 'Human Ecology Nondepartmental',
  HEBRW: 'Hebrew',
  HINDI: 'Hindi',
  HIST: 'History',
  HUNGR: 'Hungarian',
  IARD: 'International Agriculture & Rural Development',
  ILRHR: 'Human Resource Studies',
  ILRIC: 'International & Comparative Labor',
  ILRID: 'Industrial and Labor Relations Interdepartmental',
  ILRLE: 'Labor Economics',
  ILRLR: 'Labor Relations, Law and History',
  ILROB: 'Organizational Behavior',
  ILRST: 'Social Statistics',
  IM: 'Independent Major',
  INDO: 'Indonesian',
  INFO: 'Information Science',
  ITAL: 'Italian',
  JAPAN: 'Japanese',
  JPLIT: 'Japanese Literature',
  JWST: 'Jewish Studies',
  KHMER: 'Khmer',
  KOREA: 'Korean',
  LA: 'Landscape Architecture',
  LATA: 'Latin American Studies',
  LATIN: 'Latin',
  LAW: 'Law',
  LEAD: 'Leadership',
  LEGAL: 'Legal Studies',
  LGBT: 'Lesbian, Gay, Bisexual & Transgender Studies',
  LING: 'Linguistics',
  LSP: 'Latino Studies Program',
  MAE: 'Mechanical & Aerospace Engineering',
  MATH: 'Mathematics',
  MEDVL: 'Medieval Studies',
  MGMT: 'Graduate Management',
  MILS: 'Military Science',
  MSE: 'Materials Science & Engineering',
  MUSIC: 'Music',
  NACCT: 'Graduate Management Accounting',
  NAVS: 'Naval Science',
  NBA: 'Graduate Management Business Admin',
  NCC: 'Graduate Management Common Core',
  NEPAL: 'Nepali',
  NES: 'Near Eastern Studies',
  NMI: 'Graduate Management Individualized Study',
  NRE: 'Graduate Management Research',
  NS: 'Nutritional Science',
  NSE: 'Nuclear Science & Engineering',
  NTRES: 'Natural Resources',
  ORIE: 'Operations Research & Information Engineering',
  PADM: 'Public Administration',
  PALI: 'Pali',
  PAM: 'Policy Analysis and Management',
  PE: 'Physical Education & Athletics',
  PERSN: 'Persian',
  PHIL: 'Philosophy',
  PHYS: 'Physics',
  PLBIO: 'Plant Biology',
  PLBRG: 'Plant Breeding',
  PLHRT: 'Horticulture Sciences',
  PLPPM: 'Plant Pathology',
  PLSCI: 'Plant Sciences',
  PLSCS: 'Soil & Crop Sciences',
  PMA: 'Performing and Media Arts',
  POLSH: 'Polish',
  PORT: 'Portuguese',
  PSYCH: 'Psychology',
  PUNJB: 'Punjabi',
  QUECH: 'Quechua',
  RELST: 'Religious Studies',
  ROMAN: 'Romanian',
  ROMS: 'Romance Studies',
  RUSSA: 'Russian',
  RUSSL: 'Russian Literature',
  SANSK: 'Sanskrit',
  SHUM: 'Society for the Humanities',
  SINHA: 'Sinhala',
  SNLIT: 'Sanskrit Literature',
  SOC: 'Sociology',
  SPAN: 'Spanish',
  STS: 'Science & Technology Studies',
  STSCI: 'Statistical Science',
  SWAHL: 'Swahili',
  SWED: 'Swedish',
  SYSEN: 'Systems Engineering',
  TAG: 'Tagalog',
  TAMIL: 'Tamil',
  TECH: 'Digital Technology & Practice',
  THAI: 'Thai',
  TIBET: 'Tibetan',
  TOX: 'Toxicology',
  TURK: 'Turkish',
  UKRAN: 'Ukrainian',
  UNILWYL: 'Learning Where you Live',
  URDU: 'Urdu',
  VETCS: 'Veterinary Medicine Clinical Sciences',
  VETMI: 'Veterinary Medicine Microbiology',
  VETMM: 'Veterinary Medicine Molecular Medicine',
  VIEN: 'Viticulture and Enology',
  VIET: 'Vietnamese',
  VISST: 'Visual Studies',
  VTBMS: 'Veterinary Medicine BioMedical Sciences',
  VTMED: 'Veterinary Medicine Professional Curriculum',
  VTPMD: 'Vet Med Population Medicine & Diagnostic Services',
  WOLOF: 'Wolof',
  WRIT: 'Writing Program',
  YORUB: 'Yoruba',
  ZULU: 'Zulu',
};

exports.acadGroupMap = {
  AG: 'Agriculture and Life Sciences',
  AR: 'Architecture, Art and Planning',
  AS: 'Arts and Sciences',
  AT: 'Athletics',
  BU: 'Business',
  CT: 'Cornell Tech',
  CU: 'Cornell University',
  EN: 'Engineering',
  GR: 'Graduate',
  HE: 'Human Ecology',
  IL: 'Industrial and Labor Relations',
  LA: 'Law',
  OT: 'Reserve Officer Training',
  VM: 'Veterinary Medicine',
};
